version: '3'
services:
  b8r-api:
    container_name: b8rapi
    image: urvish91/betterhomes-backend:1.0.5
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=80
      - APP_KEY=
      - DB_URI=mongodb+srv://b8r_app:EsM5QXMGzuCzNKvs@cluster0.sbfwcs4.mongodb.net/b8r_home
      - API_PREFIX=/api/v1
      - TIMEZONE=IN
      - SECRET=b8r_home
      - REFRESH_SECRET=b8r_home-testing
      - JWT_EXPIRY=3d
      - HOST_URL=
      - AWS_ACCESS_KEY_ID=AKIAXFTHGIOESPHERSNW
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=ap-south-1
      - S3_BUCKET_URL=
      - S3_BUCKET_NAME=elasticbeanstalk-ap-south-1-493063914377
    ports:
      - "80:80"
